name: Publish

on:
  push:
    tags: ["**"] # Releases

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bundle.yml
    with:
      upload: true

  publish-artifacts:
    name: "Release Taymyr Antora UI"
    needs:
      - "build"
    runs-on: ubuntu-20.04
    steps:
      - name: Download bundle
        uses: actions/download-artifact@v3
        with:
          name: ui-bundle
          path: build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/ui-bundle.zip
